language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-22.0.1
    - android-24
    - extra-android-m2repository

notifications:
  slack: buchrechmc:tIyp44k1BZMDkooD8WqhgFvV

script:
    gradle build connectedCheck