language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

notifications:
  slack: buchrechmc:tIyp44k1BZMDkooD8WqhgFvV

script:
     - ./gradlew build connectedCheck