language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-23
    - android-24
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository

notifications:
  slack: buchrechmc:tIyp44k1BZMDkooD8WqhgFvV

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest
  - >
      curl
      -F "status=2"
      -F "notify=1"
      -F "notes=Some new features and fixed bugs."
      -F "notes_type=0"
      -F "ipa=@app/build/outputs/apk/app-debug_with_ci_keystore.apk"
      -H "X-HockeyAppToken: $HOCKEYAPP_TOKEN"
      https://rink.hockeyapp.net/api/2/apps/upload